### ISSUE TITLE
https://wordpress.org/support/topic/shortcode-preview?replies=1

### ISSUE THREAD

**Issue by sergiubagrin** [ThemeFuse/Unyson-PageBuilder-Extension#10]
I like the plugin, but there are 2 major issues:
1) When using the shortcodes to layout a page it doesn't generate a preview.
2)There also doesn't seem to be a way to convert page to html or edit the page in the text mode.

**Comment by rockalife** [comment]
This is a duplicate of [ThemeFuse/Unyson#170](https://github.com/ThemeFuse/Unyson/issues/170)
