### ISSUE TITLE
PageBuilder disappears after Unyson Plugin update

### ISSUE THREAD

**Issue by yura-x** [ThemeFuse/Unyson-PageBuilder-Extension#100]
Hello!
PageBuilder often disappears from post (page) edit page after Unyson Plugin update. It appears again after deleting and installing again whole Unyson Plugin or after Extensions update (when updating extensions after plugin update).
Question: How can we put admin_notice with message that we need to update Unyson Extensions after Unyson Plugin update?
Now we only have a message that extensions has to be updated at the bottom of  updates page:
[http://prntscr.com/hqva2l](http://prntscr.com/hqva2l)

Thank you very much!

**Comment by ViorelEremia** [comment]
> How can we put admin_notice with message that we need to update Unyson Extensions after Unyson Plugin update?

If unyson has an update not mean extensions also have updates.
I don't understand you very well, you mean after each update of unyson you have to update extensions?
When there are updates for extensions unyson by default get an admin notice.
Or on your site after unyson update extensions are not available. During the update, extensions are copied temporary to tmp folder after the update they are put back in extension folder. Maybe here is the problem, they are not put back.

**Comment by yura-x** [comment]
Hello! Thanks for your reply!
Sorry for inaccurate question.
I want to show a dismissable admin notice with text like "Please update your Unyson extensions" if a new version of any extension is available, in addition to the footer message on updates page (from screenshot above). 
Thank you!

**Comment by ViorelEremia** [comment]
Unyson by default has that  "Please update your Unyson extensions" see here: https://github.com/ThemeFuse/Unyson/commit/3ffa7d859d8be0c723e897dd0171f507870c4fa8
you do not have to worry about it, maybe it does not work on your site then let's see why it does not work, you do not have to build any other bikes on it. So try and reduce the version to one of the extensions and check if you have a notification(admin_notice) in your admin dashboard. And also check if you have the latest plugin version.

**Comment by yura-x** [comment]
Maybe I'm doing something wrong but I have not any notice about extensions updates available at the top of the page, only at the bottom of updates page:
[http://prntscr.com/hrgbom](http://prntscr.com/hrgbom)

**Comment by ViorelEremia** [comment]
You can't see notice because your transient is not [expired](https://github.com/ThemeFuse/Unyson/blob/master/framework/extensions/update/extensions/github-update/class-fw-extension-github-update.php#L196) by default it is 24 hours.
You can't set it too small because you can go beyond the limit imposed by github(5000/hour), unyson has now 100000 + maybe near 200.000 so the probability is very high to pass this limit(each site can make 25 requests depends on how many extensions are installed) I can reduce it to 12 hours less I can not riskk.
