### ISSUE TITLE
No bulk edit

### ISSUE THREAD

**Issue by firelite** [ThemeFuse/Unyson-PageBuilder-Extension#101]
There are many situations where I need to update multiple content elements within a page in the drag 'n' drop builder but it appears that I must make the edits for each element one by one.  I'm assuming there's no bulk editing built-in.  Is there a way I can access the visual source code via text mode?

**Comment by ViorelEremia** [comment]
There is no way to see it, but you can do some hacks, you have data json from db:
```
// Not tested
$data = fw_get_db_post_option( $post->ID, 'page-builder' );
$data['json'] = str_replace( 'x', 'y', $data['json'] );
update_post_meta( $post->ID, 'page-builder', $data );
```
How to savfe it see here for seo implimentation(after all changes or refresh admin page after save it): https://github.com/ThemeFuse/Unyson-PageBuilder-Extension/blob/master/class-fw-extension-page-builder.php#L174
