### ISSUE TITLE
Nesting Grids

### ISSUE THREAD

**Issue by firelite** [ThemeFuse/Unyson-PageBuilder-Extension#102]
Is it possible to nest grids within grids?  For example, an 8 column row placed within a 6 column row?

**Comment by ViorelEremia** [comment]
What you want to do? 
At level php you cant do that.
html you can try should work.

**Comment by firelite** [comment]
I'm talking about using the drag n drop builder feature as the user.    The nature of layout elements appears to only be able to be dropped within a Section element.  There's many scenarios when it's necessary to nest a layout element within another layout element.  See the image to see what the restriction is:

<img width="2231" alt="unyson builder grid problem" src="https://user-images.githubusercontent.com/2793637/34999586-f678f58e-fa96-11e7-8454-a02f8f83e59c.png">


1/2 Column layout element cannot be dropped into 3/4 Column layout element.

Can this behavior be added to the builder?

**Comment by ViorelEremia** [comment]
Yes, I know about that, it is related to:https://github.com/ThemeFuse/Unyson/issues/2485 
I will soon solve it, at the moment it is not possible.
