### ISSUE TITLE
Add Attribute to grid row/col

### ISSUE THREAD

**Issue by ecksite** [ThemeFuse/Unyson-PageBuilder-Extension#106]
Is it possible to add a html attribute to the row or col container of the pagebuilders grid?
something like:

` $cfg['grid.row.attr'] = 'myattribute'; `

If not, could you add something like that please?

**Comment by ViorelEremia** [comment]
Why do you need that? That shortcode row you can not add options for it so to add a attribute you need to add it depending on an option. Or you want to add for all?

**Comment by ecksite** [comment]
I am trying to add the uikit 3 grid, so I would like to add the uk-grid attribute in order to use the js options.

See: https://getuikit.com/docs/grid

**Comment by ViorelEremia** [comment]
Have you tried to rewrite row view.php? 
How do you think it will be the best way to do this?

**Comment by ViorelEremia** [comment]
It is good! I do not see another way of improvement.
