### ISSUE TITLE
Pagebuilder UI

### ISSUE THREAD

**Issue by sergiubagrin** [ThemeFuse/Unyson-PageBuilder-Extension#13]
Different icons in pagebuilder: 

1. http://screencast.com/t/P8mybPt23r
2. http://screencast.com/t/eycxVqp5sV

**Comment by GheorgheP** [comment]
https://github.com/ThemeFuse/Unyson-PageBuilder-Extension/commit/39f0268e58ca938bdd660e3dadfeb0b4a05c8a72
