### ISSUE TITLE
Page Templates

### ISSUE THREAD

**Issue by DimiBaitanciuc** [ThemeFuse/Unyson-PageBuilder-Extension#16]
Aici la templates nu e cum trebuie: http://joxi.ru/zANBp7Miv05NA9, noi facusem altfel initial. Asa nu e functional, trebuie sa avem posibilitatea sa facem Save la un template.

**Comment by moldcraft** [comment]
A fost reparat https://github.com/ThemeFuse/Unyson-PageBuilder-Extension/issues/14 o sa fie live vineri https://github.com/ThemeFuse/Unyson-Extensions-Approval/issues/18
