### ISSUE TITLE
DIFFERENT SIZE for same shortcode

### ISSUE THREAD

**Issue by sergiubagrin** [ThemeFuse/Unyson-PageBuilder-Extension#17]
1. http://screencast.com/t/oKHOpDEH6

2. http://screencast.com/t/1sUde7h98d

**Comment by moldcraft** [comment]
*Info: Use the latest (git) version of Unyson (it has changes/fixes for modal sizes)*

The problem is that some shortcodes options modal have different sizes in page-builder and shortcode-editor. It's needed to find out why this happens.

**Comment by GheorgheP** [comment]
https://github.com/ThemeFuse/Unyson-Forms-Extension/commit/ef1e0342359269f5833a16b385e36ca97305f701
