### ISSUE TITLE
It is needed to change icons for Page Builder and Shortcode editor

### ISSUE THREAD

**Issue by sergiubagrin** [ThemeFuse/Unyson-PageBuilder-Extension#19]
1. http://screencast.com/t/b1Ga0Fs7fu

2. http://screencast.com/t/4HJsSNRapWw

**Comment by GheorgheP** [comment]
https://github.com/ThemeFuse/Unyson-PageBuilder-Extension/commit/39f0268e58ca938bdd660e3dadfeb0b4a05c8a72

**Comment by flody** [comment]
Sorry for my last comment/pull request. It is not related to this issue. I just made a mistake referencing the pull request (issue 19 but for shortcode extention).
