### ISSUE TITLE
how do i make vertical option page ?

### ISSUE THREAD

**Issue by xpeeder** [ThemeFuse/Unyson-PageBuilder-Extension#23]
i have planed to use you framework my next project :)
i have tried scratch theme. its  displayed theme options with tab.
i have search your documentation but i dont find how i make theme options  in vertical.

but i saw vertical now live in trello

can you please tell me how i can make theme options vertical.

Thanks

**Comment by moldcraft** [comment]
[v2.1.23](https://github.com/ThemeFuse/Unyson/releases/tag/v2.1.23)

**Comment by dinhtungdu** [comment]
How about the page/post options and taxonomy option, can they be vertical too?

**Comment by moldcraft** [comment]
No
