### ISSUE TITLE
Issues with the latest releases...

### ISSUE THREAD

**Issue by 2Fwebd** [ThemeFuse/Unyson-PageBuilder-Extension#28]
Hi there,

I got many feedbacks from customers and I got the same issue to... Actually with the latest version of Wordpress, Unyson and Unyson extensions, We can no longer edit the content from the Page Builder, the shortcodes are there (we can see it once the page builder is disabled) but doesn't seem to be interpreted by Unyson page builder..
Example : 
http://2f-design.fr/dev/starry-dev/about-us/
![edit_page_ _starry_ _wordpress](https://cloud.githubusercontent.com/assets/5446124/7137787/5f0abde4-e2bc-11e4-8c89-248f16bda6c1.jpg)

I can send you access to the dashboard if you can't reproduce the error. 

Feedback from one of the customers : 

> "I've noticed something weird that happened more than once: Unyson loses the ability to read its own pages :( On the first go I re-created the page, but on the second that becomes a pain, as I have put a lot of work into its current state. So the page exists (galactichistorian.com/love), looks well but Unyson doesn't detect its blocks in the editor anymore. Any ideas?"

Other "similar" issue
> "While editing my website I click to go to a revised version I was working on a matter of minutes ago. Once I'd gone back to the Visual Builder screen. All my content had gone into one single text box which does not allow me to edit the website ...
Have you had this issue before? Can it be fixed? In not I'll have to do a lot of work again."

Thank you for the help, I have no idea about how that happens because on some other pages it seems to work well ... Moreover, as I said the shortcodes are still here. Let me know if I can help you about this issue.

Best regards,

2F

**Comment by GheorgheP** [comment]
https://github.com/ThemeFuse/Unyson/issues/424
