### ISSUE TITLE
Icon change

### ISSUE THREAD

**Issue by DimiBaitanciuc** [ThemeFuse/Unyson-PageBuilder-Extension#29]
I'd like us to change the pen icon http://joxi.ru/Q2KqDkgSvZG9rj for the edit function with a gear one http://joxi.ru/8AnN51aiy6gNAO. Bogdan pointed out that it was hard for him to figure out that the columns and we think changing the icon will help a bit, people being more accustom with a gear icon for settings. 

When it will come to this please give me a sign on skype and I'll give you the exact icon to put there. Thanks.

**Comment by moldcraft** [comment]
[This](https://developer.wordpress.org/resource/dashicons/#admin-generic) ?

**Comment by DimiBaitanciuc** [comment]
Yes

**Comment by moldcraft** [comment]
[This](https://static.md/e5d5e7c2a14465f06f982fde797bab94.png) is ok?
