### ISSUE TITLE
Is it possible to get page builder info for current page?

### ISSUE THREAD

**Issue by NazarkinRoman** [ThemeFuse/Unyson-PageBuilder-Extension#32]
Hello!

Is it possible to ensure that page builder is used on current page(to load other page template instead of standard) and get a list of widgets on page(or just ensure there is a some widget is used or not)?

Thanks in advance.

**Comment by moldcraft** [comment]
> Is it possible to ensure that page builder is used on current page

[Yes](https://github.com/ThemeFuse/Unyson-PageBuilder-Extension/blob/59e90aa2458229990e385f8c956a4c0a94e442bd/helpers.php#L3-L9)

> get a list of widgets on page

I don't know, I am not familiar with Sidebars and widgets.

**Comment by NazarkinRoman** [comment]
Hmm.. As a temporary solution I've used standard wordpress `has_shortcode` function. This builder based on shortcodes, so all elements is shortcodes too and we can use core functions to work with them.

But still looking for more elegant solution..
