### ISSUE TITLE
Extra update button appeared after latest unyson update

### ISSUE THREAD

**Issue by ierpe** [ThemeFuse/Unyson-PageBuilder-Extension#35]
Hey, not 100% sure it's related, but I just updated to unyson 2.4.3, updated the extensions, and now I have this extra update button lying on the visual builder

![edit page ad s up wordpress](https://cloud.githubusercontent.com/assets/790992/8931456/bcc07c04-3536-11e5-87b5-92c0848f29d0.png)

**Comment by moldcraft** [comment]
It seems that you have Builder extension dev version. That [button was added](https://github.com/ThemeFuse/Unyson-PageBuilder-Extension/issues/34) but we haven released a new version yet.

**Comment by ierpe** [comment]
Ah yes... we are using a script to clone all extensions directly from github, since the interface installation always creates folder permission issues and won't install...
