### ISSUE TITLE
Avoid the user to put an element in a column with a specific size

### ISSUE THREAD

**Issue by alvisir** [ThemeFuse/Unyson-PageBuilder-Extension#38]
Hi, 
is it possible to avoid the user to put an element in a column with a specific size?
For example an element that requires only a full-width layout to better display its content.
The idea would be to display an alert when the column does not match the requirements of the inserted element.

**Comment by moldcraft** [comment]
Hello,

This method does the trick https://github.com/ThemeFuse/Unyson-Builder-Extension/blob/e07cd70ea1ea8a0179078ba6be4d616c9bc732c5/includes/option-types/builder/static/js/builder.js#L688-L696

Here it is in Column https://github.com/ThemeFuse/Unyson-Shortcodes-Extension/blob/65e595ae84684b330a4161cef4afc1df538a7ddc/shortcodes/column/includes/page-builder-column-item/static/js/scripts.js#L136-L138

Unfortunately id doesn't have the possibility to restrict by item properties, only by type.

Anyway, what will happen when the column will be resized to that restricted size, what will happen with inner elements that shouldn't be there?

----

Maybe I simpler solution would be to hide the restricted item from css (in frontend) when the column has a certain size?

**Comment by alvisir** [comment]
Thank you for reply. In my case the restriction by type is enough.
About the issue of inner elements, is it possible to add a js alert that warns the user and blocks the resize? The css solution is pretty good but I prefer to avoid the issue only from backend.

**Comment by moldcraft** [comment]
I added an event https://github.com/ThemeFuse/Unyson-Shortcodes-Extension/compare/v1.3.4...3006a34acc3023e0169a5024429d73087a9bbdc0#diff-9dcef477f9fa28c8d82e1ac4d1c8d396L136


Download the latest dev version of [Shortcodes](https://github.com/ThemeFuse/Unyson-Shortcodes-Extension) in `unyson/framework/extensions/shortcodes` and try the following

```js
fwEvents.on('fw:builder:page-builder:column:filter:allow-incomming-type', function(data){
    if (...) {
        data.allow = false;
    }
});
```

**Comment by alvisir** [comment]
Hi, sorry for the delay. Nice, but where do I put the last piece of code you wrote?
