### ISSUE TITLE
the_excerpt comes out empty

### ISSUE THREAD

**Issue by sergiubagrin** [ThemeFuse/Unyson-PageBuilder-Extension#4]
Hi @sergiubagrin , thanks for all the great work you do.
I have a question regarding the page builder.
Right now, every time I use the page builder in a post or page, the_excerpt comes out empty. Is there a way to display the excerpt?

This is related to the page builder elements not being output in the standard editor.

Thanks

**Comment by zakirsajib** [comment]
No good.
