### ISSUE TITLE
Customizing Simple Item Type

### ISSUE THREAD

**Issue by andreiglingeanu** [ThemeFuse/Unyson-PageBuilder-Extension#40]
Hi,

I'm trying to add some custom functionallity to [**Simple Item Type**](https://github.com/ThemeFuse/Unyson-PageBuilder-Extension/blob/0a7e1a49978cc7a53480a279aedfd96d821c831f/includes/page-builder/includes/item-types/simple/static/js/scripts.js) [modal](https://cloud.githubusercontent.com/assets/2979628/11396981/91cafee2-937e-11e5-88f8-abbd1a06cb10.png).

It would be nice if I'll have the possibility to rewrite entire `ItemView`. I've tried it, and it works, but [this](https://github.com/ThemeFuse/Unyson-Builder-Extension/blob/master/includes/option-types/builder/static/js/builder.js#L55) error [pops up](https://www.dropbox.com/s/x86mezxymuw0oe4/Screenshot%202015-11-25%2014.15.11.png?dl=0), and I'm worried about it.

I'm pretty sure that an triggered event for when the modal is ready will fulfill all my needs.

Also, I'm planning to add this custom functionallity to the **Column Item Type**, **Section Item Type** and **Contact Form** one. So maybe provide a way to rewrite those item types? I'm aware of the fact that this may break future updates so you check out the option of adding a custom event.

Thank you.

**Comment by moldcraft** [comment]
> an triggered event for when the modal is ready will fulfill all my needs

https://github.com/ThemeFuse/Unyson/issues/1042#issuecomment-159579738

download the latest dev version of Unyson and PageBuilder extension, execute `fwEvents.debug(true)` in browser console and click to open the modal.

**Comment by moldcraft** [comment]
Please give concrete examples of which custom functionallity do you want to add

**Comment by andreiglingeanu** [comment]
I want to add a rudimentary preview functionality for every shortcode. I'll handle all the html fetching, css and js initialization of them by myself. Hope to create something as general as possible.

By the way, event like `fw:builder-type:page-builder:item-type:simple:sub-type:button:options-modal:open` looks too specific to me. Not sure how to attempt the realisation, maybe create a registry of shortcodes I'll have to attach an *Preview* to, some list like data structure. Another option is to add another, more general event, like `fw:builder-type:page-builder:item-type:simple:options-modal:open` that will be triggered when any options modal will be rendered, the info about the shortcode should be passed as an argument in this case.

**Comment by moldcraft** [comment]
Trimite te rog pe `moldcraft[at]email.com` explicatie in română ce anume vreti sa facei ca nu prea inteleg.

**Comment by rockalife** [comment]
Hi @andreiglingeanu

I think that what you are trying to do is a bad idea, and here is why:
* Even if the user would have the shortcode's preview in the modal, he would still need to preview the whole page to see if the shortcode fits in (design wise) with the rest of it.
* There might occur some inconsistencies if a shortcode is built to look and / or behave differently in various contexts. E.g. a shortcode might adapt itself if put inside a large (or small) column and so the preview inside the modal could show it in one way, different than the real result.
* This feature requires a lot of work but the result is (IMHO) just not worth it.

Just my 2 cents.

**Comment by danyj** [comment]
@andreiglingeanu bud , you are on the right track , I cant disclose what I did at this moment, but it is worth it. and the way to do it is dont mess with the modal open/close/render events  but rather create own option type that would sum up everything. 


hint in creating that kind of option type, 

all you need to save is 

html
css
json , 

you dont need to save 50 options but 3 , but you can have preview of 50 that would generate those main 3. I think you know where I am going with this.

**Comment by moldcraft** [comment]
*Please download the latest dev version of Shortcodes, PageBuilder and Builder extensions. There were made some css fixes related to controls.*

##### How to add a new control for simple item

```js
function onControlClick(data) {
    console.log(data);
}

fwEvents.on('fw:builder-type:page-builder:item-type:simple:controls', function(data){
    if (data.shortcode != 'button') {
        return;
    }
    
    jQuery('<i class="unycon unycon-unyson" data-hover-tip="Hello"></i>')
        .on('click', function(e){
            e.stopPropagation(); // prevent options modal open
            
            onControlClick(data);
        })
        .prependTo(data.$controls);

    /*data.$controls.prepend( // test controls, to see that they are aligned properly
        '<i class="unycon unycon-unyson" data-hover-tip="Hello"></i>'+
        '<i class="fa fa-file" data-hover-tip="Hello"></i>'+
        '<i class="fa fa-btc" data-hover-tip="Hello"></i>'+
        '<i class="unycon unycon-rectangle" data-hover-tip="Hello"></i>'
    );*/
});
```

**Comment by moldcraft** [comment]
Let me know if you need something else, if not, please close this issue.

**Comment by andreiglingeanu** [comment]
@moldcraft What you mean by downloading the dev version? Just redownload from unyson menu will not do? Do I have to download them manually into wp-content/plugins/unyson?

**Comment by andreiglingeanu** [comment]
Your [suggestion](https://cloud.githubusercontent.com/assets/2979628/11428707/1535c7e6-9477-11e5-93fa-c296a9a113d8.png) is not what I need. [This](https://cloud.githubusercontent.com/assets/2979628/11428733/4daf7fe0-9477-11e5-9536-08851e31834e.png) is what I try to accomplish.

That's how I'm doing it now:
```javascript
jQuery(function () {
	var $ = jQuery;
	var PREVIEW_MODAL_ID = 'ct-shortcode-preview-modal';

	fwEvents.on('fw:builder-type:page-builder:item-type:simple:sub-type:button:options-modal:open', function (builder) {
		var $modal = builder.modal.frame.$el;

		var shortcodeName = 'button';

		$modal.find( '.ct-button-open-preview' ).remove();

		var $button = $( '<button />', {
			class: 'button media-button button-large button-open-preview',
			html: 'Preview',
			type: 'button'
		})
			.data( 'shortcode-name', shortcodeName )
			.insertBefore(
				$modal.find( '.button-primary' )
			);
	});

	$( document ).on('click', '.button-open-preview', function (e) {
          // process preview
	});
});
```

Thanks.

**Comment by moldcraft** [comment]
Well, next time better create a screenshot with annotations.

**Comment by moldcraft** [comment]
Well, next time better create a screenshot with annotations.

Ok, I will check if it's possible to create an event to register custom buttons there.

**Comment by andreiglingeanu** [comment]
@rockalife I agree that it's possible to create inconsistencies between modal and the main page, but it's a matter of properly inserting some css. At least I'll try it.

@danyj Didn't get your idea. Why I would need a new option type here?

@moldcraft Okay, thanks.

**Comment by danyj** [comment]
@andreiglingeanu  forget my idea I am bound by the contract not to disclose it before theme release , 
what you are doing is not bad at all , actually we should have something like this by default, sure optional but doable , 

on preview click render shortcode preview with it's CSS js dependencies. and I see you are on the way to acomplish this here https://github.com/ThemeFuse/Unyson-Shortcodes-Extension/issues/39

@moldcraft   bud this is step closer to visual  reference which is a key given the magnitude of options that we are trowing at our future users. Please consider it as an option for shortcodes. 

In shortcode config we can add a param 

    preview => true

**Comment by andreiglingeanu** [comment]
@danyj In order to give this option by default we have to create an unified way of adding custom dynamic css. Until then, every realisation of preview feature will be bound to the theme way of adding dynamic css.

The part with JS should be solved with some sort of event that will trigger every JS action.

**Comment by danyj** [comment]
@andreiglingeanu  there is already a way to do dynamic css/js , I have been using since moldcraft made it happened couple months back 
https://github.com/ThemeFuse/Unyson/issues/275#issuecomment-94061237


http://manual.unyson.io/en/latest/extension/shortcodes/index.html?highlight=dynamic#enqueue-shortcode-dynamic-css-in-page-head 

and loading the shortcode  css/js files goes trough shortocde static.php anyway ,

**Comment by andreiglingeanu** [comment]
@danyj Yep, I'm already testing if capturing css from `fw_ext_shortcodes_enqueue_static:{name}` works well. Will come up with feedback.

**Comment by danyj** [comment]
@andreiglingeanu   note that for shortocdes with dash in a name , you need to use an underscore like this for example 


    fw_ext_shortcodes_enqueue_static:special_heading //  instead special-heading

**Comment by moldcraft** [comment]
https://github.com/ThemeFuse/Unyson/commit/4dfcaea0048578143a453394bf569704be615575

```js
var modal = new fw.OptionsModal({
    options: {'test': {type: 'text'}}
}, {
    buttons: [
        {
            style: '',
            text: 'Hello',
            priority: 39,
            click: function () { console.log('Hello'); }
        }
    ]
});
modal.open();
```

----

https://github.com/ThemeFuse/Unyson-PageBuilder-Extension/commit/f9a37432903d944a2e2c9cd4deec3bf41de5cbd3

```js
fwEvents.on('fw:builder-type:page-builder:item-type:simple:options-modal:settings', function(data){
    if (data.shortcode != 'button') {
        return;
    }

    data.modalSettings.buttons.push({
        style: '',
        text: 'Hello',
        priority: 39,
        click: function () { console.log('Hello'); }
    });
});
```

**Comment by moldcraft** [comment]
Is there anything else that needs to be done on this issue?

**Comment by andreiglingeanu** [comment]
@moldcraft Very cool :+1: I guess we are done. Let's close it.

**Comment by danyj** [comment]
@andreiglingeanu if you dont mind share what you have once done please. I cant share mine until theme is out but will gladly do so afterwards.

**Comment by danyj** [comment]
suggestion ,  add option for button location and typoe ( link or button ) ,  header of footer http://prntscr.com/9c6i9e
in your latest theme Themefuse added links to docs  next to close modal button which I find very useful. 
http://prntscr.com/9c6jyd

**Comment by moldcraft** [comment]
It already exists but it's not documented

```php
$cfg = array(
    'page_builder' => array(
        'title'       => __( 'Shortcode Title', 'the-core' ),
        'description' => __( 'Description...', 'the-core' ),
        'tab'         => __( 'Content Elements', 'the-core' ),

        'popup_header_elements' => '<a href="#" target="_blank"><span class="dashicons dashicons-editor-help"></span> '. __('Go to Docs', '...') .'</a>',
        'popup_header_elements' => 'any html ...',
    )
);
```

**Comment by danyj** [comment]
>It already exists but it's not documented

thank you! :+1:   would be nice to see it in the docs. just in case someone else needs it.
