### ISSUE TITLE
Important Drag Bug

### ISSUE THREAD

**Issue by smemis** [ThemeFuse/Unyson-PageBuilder-Extension#46]
<a href="http://www.screencast.com/t/bKhy7pvKbt" target="_blank">http://www.screencast.com/t/bKhy7pvKbt</a>

How can i fix this bug?

It is very important, beacuse I can not build a page with this huge bug :(

Please a solution.

Thanks.

**Comment by moldcraft** [comment]
This problem was always there. You just need to move the mouse faster.

https://github.com/ThemeFuse/Unyson-PageBuilder-Extension/issues/25
