### ISSUE TITLE
Builder vs PageBuilder

### ISSUE THREAD

**Issue by smemis** [ThemeFuse/Unyson-PageBuilder-Extension#47]
Hi;
Please can you explain, what difference Builder Extension vs PageBuilder Extension?

Thanks

**Comment by moldcraft** [comment]
Hello,

[Builder](http://manual.unyson.io/en/latest/extension/builder/index.html) provides the core functionality for all builders, at the moment we have: Page Builder, Form Builder and Learning Quiz Builder.
