### ISSUE TITLE
How I can add configurations panel for other layout elements?

### ISSUE THREAD

**Issue by sulmanpucit** [ThemeFuse/Unyson-PageBuilder-Extension#49]
Section element has got configuration option. http://d.pr/i/161Cv

How we can add same for other layout elements such as 1/1 or 1/2?

**Comment by moldcraft** [comment]
create `{theme}/framework-customizations/extensions/shortcodes/shortcodes/column/options.php`

**Comment by sulmanpucit** [comment]
Thanks :)
