### ISSUE TITLE
How short-codes are registered?

### ISSUE THREAD

**Issue by sulmanpucit** [ThemeFuse/Unyson-PageBuilder-Extension#52]
I have got a noob question. Can you tell me how short-codes are registered? For example, if I want to use map short-code in widget or somewhere else, how I can do that? Is there 

[map attributues ... ] [/map] type thing?

**Comment by moldcraft** [comment]
Hello, unfortunately PageBuilder shortcodes besides simple text/number attributes values, has complex [array attributes](https://github.com/ThemeFuse/Unyson-Shortcodes-Extension/blob/v1.3.12/shortcodes/map/options.php#L7-L8) json+htmlspecialchars encoded and are very hard to construct manually, also WordPress changes some special characters created by htmlspecialchars and corrupts the value if it is used as text in default editor. So the only way to use PageBuilder shortcodes is only in PageBuilder.

**Comment by sulmanpucit** [comment]
Thanks.
