### ISSUE TITLE
frontend-grid.css file

### ISSUE THREAD

**Issue by Jelena1** [ThemeFuse/Unyson-PageBuilder-Extension#53]
This file is in this path: unyson/framework/extensions/builder/static/css/frontend-grid.css  

I'm not sure where is that from, because nowhere on github it doesn't exists, not in Unyson or here in Unyson page builder extension. It just appears when plugin is downloaded from WP repository. 

I needed lot of time to find what is going on...

Problem is that I've found one important change in this file, but newer found it in "history" here.... (like I didn't find file also..) .... For manifest number 1.2.1 version in page builder extension, this file had this (commented!) code:

/*@media (min-width: 768px) {
    .fw-container {
        width: 750px;
    }
}
@media (min-width: 992px) {
    .fw-container {
        width: 970px;
    }
}
@media (min-width: 1200px) {
    .fw-container {
        width: 1170px;
    }
}*/

Today I updated p.builder extension and my theme has been broken. I discovered that now in manifest 1.2.2 version for page builder extension, this code is not commented anymore and fw-container class has max-width: 100%; code added.

And this broke my theme because I used additional classes for frontend!

Can you please tell me where this change can be seen? Like I said, there is difference between manifest 1.2.1 and newest 1.2.2 version for builder extension in this file.

Can  you please explain how important is this change because I want to remove it again for my theme because it breaks it?

Thank you.

**Comment by Jelena1** [comment]
https://github.com/ThemeFuse/Unyson-Builder-Extension/commit/30ff8464e83f567e645c47a944c93379d4e8a21e  just found this... can my question be answered there?

**Comment by moldcraft** [comment]
1. The file is in Builder extension

    https://github.com/ThemeFuse/Unyson-Builder-Extension/blob/master/static/css/frontend-grid.css

2. The change comes from here

    https://github.com/ThemeFuse/Unyson-Builder-Extension/pull/21

3. You can fix this like that:

    1. Copy `frontend-grid.css` to `{theme}/framework-customizations/extensions/builder/static/css/frontend-grid.css`

    2. Create `{theme}/framework-customizations/extensions/builder/static.php` with the following contents

        ```php
        <?php if (!defined('FW')) die('Forbidden');

        if (!is_admin()) {
        	wp_register_style(
        		'fw-ext-builder-frontend-grid',
        		fw_ext('builder')->locate_URI('/static/css/frontend-grid.css'),
        		array(),
        		fw_ext('builder')->manifest->get_version()
        	);
        }
        ```
