### ISSUE TITLE
Optimize drag & drop page-builder

### ISSUE THREAD

**Issue by duongancol** [ThemeFuse/Unyson-PageBuilder-Extension#54]
Hi! Is there any ways to optimize this step, sometimes it's really a nightmare when we build page by page-builder. You could see the screencast [here](https://monosnap.com/file/K5NLrEBSd3ibarstjKQ3UmdCKXjNiz)

**Comment by moldcraft** [comment]
https://github.com/ThemeFuse/Unyson-PageBuilder-Extension/issues/25

A workaround is to move the mouse faster.
