### ISSUE TITLE
cant get page content of blog page

### ISSUE THREAD

**Issue by ahm-3d** [ThemeFuse/Unyson-PageBuilder-Extension#58]
i have created a page "Blog" and set it as the front page for all my blogs.

i have also created a content element that retrieves all the blog posts.

i have tried to modify the index.php to output the_content of the Blog page, however the page displays blank:

```
<?php $object = get_queried_object();
	$post = get_post($object->ID);
	$content = apply_filters('the_content', $post->post_content);
	echo $content; ?>
```

if there a way to display all the page builder element that i have added into the Blog page?

**Comment by moldcraft** [comment]
https://github.com/ThemeFuse/Unyson/issues/1549#issuecomment-219377267
