### ISSUE TITLE
Visual Page Builder (Unyson) doesnt appear on my page

### ISSUE THREAD

**Issue by priondaruu** [ThemeFuse/Unyson-PageBuilder-Extension#65]
hi, i got a trouble when edit my content because visual page builder was disappear on the page. there was a Visual Page Builder button but when i click it doesnt appear the layout element, content element, media element and theme blossom tabs. but on other page like issue, visual page builder work properly, why only on the page visual builder disappear/cant load menu? please help me @moldcraft @alexluncashu :D

visual page builder disappear on page
![pic1](https://cloud.githubusercontent.com/assets/21008681/17643560/82fc9852-6197-11e6-9de7-fea5a02f1003.png)

on issue visual page builder work properly
![picc2](https://cloud.githubusercontent.com/assets/21008681/17643550/33880522-6197-11e6-8b23-62ca4dba7c5e.png)

**Comment by moldcraft** [comment]
Hello,

Please run this in your browser console

```php
jQuery('#fw-options-box-page-builder-box > .hndle').trigger('click');
```

**Comment by priondaruu** [comment]
@moldcraft where i can find browser console? sorry im just a newbie :)

**Comment by priondaruu** [comment]
@moldcraft OH GOD IT WORK!! i really desperated about it then you give me a hope!! you are my savior!! damn i really happy hahaa.. thanks!! god bless you and your family!!

**Comment by Delfina10** [comment]
I have a similar problem. Page builder was there then stop appearing in pages. 

![screen shot 2019-01-24 at 12 24 50 pm](https://user-images.githubusercontent.com/47006611/51701375-5540f800-1fdf-11e9-8245-3521e66102cf.png)
