### ISSUE TITLE
Dynamic grid on tablet

### ISSUE THREAD

**Issue by dmbostan** [ThemeFuse/Unyson-PageBuilder-Extension#66]
Hi, guys!

I was wondering how can I achieve the following:

On desktop I have this:
[http://prntscr.com/cfia9r](http://prntscr.com/cfia9r)

But on tablet, I need to achieve this:

[http://prntscr.com/cfib4r](http://prntscr.com/cfib4r)

Is this possible with Unyson Page Builder?

**Comment by moldcraft** [comment]
You create your own column sizes by overwriting [this config](https://github.com/ThemeFuse/Unyson-Builder-Extension/blob/3ef46e296ad54e2cdd9401e0c447fec1728b4013/config.php#L17) in your theme http://manual.unyson.io/en/latest/extension/builder/index.html#changing-the-grid

**Comment by dmbostan** [comment]
Yes, I can. But can the user add this classes from the builder? Designs are always different. Let's say on desktop it is 8+4. What if there is a need for a row to be 4+8, and another row 6+6? Adding classes to config will not allow selecting custom values.

**Comment by moldcraft** [comment]
The only solution the framework can offer is to add these in builder config:

```php
'1_3_1_2' => array(
	'title'          => '1/3 (1/2)',
	'backend_class'  => 'fw-col-sm-4 fw-col-xs-6',
	'frontend_class' => 'fw-col-sm-4 fw-col-xs-6',
),
'1_3_1_1' => array(
	'title'          => '1/3 (1/1)',
	'backend_class'  => 'fw-col-sm-4 fw-col-xs-12',
	'frontend_class' => 'fw-col-sm-4 fw-col-xs-12',
),
```

But it can be confusing

**Comment by dmbostan** [comment]
True.
But can I add to 2 fields (input or select) to each column and call them Tablet and Mobile and output their values on the front-end?

**Comment by moldcraft** [comment]
You can [overwrite column shortcode options and view in theme](http://manual.unyson.io/en/latest/extension/shortcodes/index.html#overwriting-shortcodes)

**Comment by dmbostan** [comment]
Oh, boy! This is even better :)

Shortcode's name is Column ?

**Comment by moldcraft** [comment]
Yes `column`

**Comment by dmbostan** [comment]
Any hint what file to edit/overwrite?

**Comment by moldcraft** [comment]
Please read [the docs](http://manual.unyson.io/en/latest/extension/shortcodes/index.html)

```php
{theme}/framework-customizations/extensions/shortcodes/shortcodes/column/option.php
{theme}/framework-customizations/extensions/shortcodes/shortcodes/column/views/view.php
```
