### ISSUE TITLE
[solved] WP editor JS issue

### ISSUE THREAD

**Issue by dmbostan** [ThemeFuse/Unyson-PageBuilder-Extension#67]
[Screenshot](http://prntscr.com/cfkesm)

Just installed Unyson on my localhost. Activated only Page Builder, Shortcodes and Sidebars.

The WYSIWYG is not working properly.

**Comment by dmbostan** [comment]
any results on this one?

**Comment by andreiglingeanu** [comment]
Works perfectly on my side. Please test it with latest Unyson master.

**Comment by moldcraft** [comment]
You can also try to reinstall WordPress Shortcodes extension.

**Comment by dmbostan** [comment]
Thanks for the recommendation!

However, issue happens because of the disable emojis snippet. Any way, we could avoid this ?

function b4u_disable_emoji() {
  	remove_action( 'admin_print_styles', 'print_emoji_styles' );
  	remove_action( 'wp_head', 'print_emoji_detection_script', 7 );
  	remove_action( 'admin_print_scripts', 'print_emoji_detection_script' );
  	remove_action( 'wp_print_styles', 'print_emoji_styles' );
 	remove_filter( 'wp_mail', 'wp_staticize_emoji_for_email' );
	remove_filter( 'the_content_feed', 'wp_staticize_emoji' );
	remove_filter( 'comment_text_rss', 'wp_staticize_emoji' );
	add_filter( 'tiny_mce_plugins', 'disable_emojicons_tinymce' );
}
add_action( 'init', 'b4u_disable_emoji' );

function disable_emojis_tinymce( $plugins ) {
	if ( is_array( $plugins ) ) {
		return array_diff( $plugins, array( 'wpemoji' ) );
	} else {
		return array();
	}
}`
`

**Comment by dmbostan** [comment]
fixed. please close this issue.
