### ISSUE TITLE
$atts['id'] returning null

### ISSUE THREAD

**Issue by dmbostan** [ThemeFuse/Unyson-PageBuilder-Extension#71]
I tried to implement a rgba color picker field and use dynamic css via  http://manual.unyson.io/en/latest/extension/shortcodes/index.html#enqueue-shortcode-dynamic-css-in-page-head

but got stuck on a strange issue:  $atts['id'] returning `null`

view.php

`<div id="shortcode-<?php echo esc_attr($atts['id']); ?>" class="<?php echo esc_attr($class); ?>">
	<?php echo do_shortcode($content); ?>
	<?php var_dump($atts['id']); ?>
</div>
`

and options.php

`

$options = array(
	
	'demo_text' => array(
		'label'   => __('Demo Text444', 'unyson'),
		'desc'    => __('This is just a demonstration. To actually make use of the options you must edit the view file.', 'unyson'),
		'type'    => 'text'
	),
	'demo_select' => array(
		'label'   => __('Demo Select', 'unyson'),
		'desc'    => __('This is just a demonstration. To actually make use of the options you must edit the view file.', 'unyson'),
		'type'    => 'select',
		'choices' => array(
			'one'   => __('Choice One', 'unyson'),
			'two'   => __('Choice Two', 'unyson'),
			'three' => __('Choice Three', 'unyson'),
		)
	),
	'bg_color' => array(
	    'id'    => array( 'type' => 'unique' ),
	    'type'  => 'rgba-color-picker',
	    'value' => 'rgba(255,0,0,0.5)',
	    'attr'  => array( 'class' => 'custom-class', 'data-foo' => 'bar' ),
	    'palettes' => array( '#ba4e4e', '#0ce9ed', '#941940' ),
	    'label' => __('Label', 'unyson'),
	    'desc'  => __('Description', 'unyson'),
	    'help'  => __('Help tip', 'unyson'),
	)
);
`

**Comment by andreiglingeanu** [comment]
Add `'id' => array('type' => 'unique')` to your `options.php`.

**Comment by dmbostan** [comment]
bg_color' => array(
        'id'    => array( 'type' => 'unique' ), 
...`
`
