### ISSUE TITLE
Write CSS and JS to files and enqueue to front

### ISSUE THREAD

**Issue by dmbostan** [ThemeFuse/Unyson-PageBuilder-Extension#72]
Hey!

After a week of Unyson, I am starting to love it :D

However, there is one more thing I would like to know:

Unyson can write CSS to HTML head inside `<style>` tag.

But can it write all the CSS inside a file, specific for the shortcode?

For example, sections could use `/theme/framework-customizations/extensions/shortcodes/shortcodes/section/static/css/styles.css`

**Comment by andreiglingeanu** [comment]
https://github.com/ThemeFuse/Unyson-Shortcodes-Extension/issues/62

**Comment by dmbostan** [comment]
Thanks!
