### ISSUE TITLE
Add Builder in theme options

### ISSUE THREAD

**Issue by dmbostan** [ThemeFuse/Unyson-PageBuilder-Extension#73]
I know this might sound a little bit crazy, but ...

Is there a way to add page builder to theme settings?

**Comment by andreiglingeanu** [comment]
Page Builder is a simple [option type](https://github.com/ThemeFuse/Unyson-PageBuilder-Extension/blob/master/class-fw-extension-page-builder.php#L120). You should be able to add it nearly everywhere where you can render an option type. 

```php
'id' => array(
	'label'              => false,
	'desc'               => false,
	'type'               => 'page-builder',
	'editor_integration' => false, // Don't even try to set this to true, you're warned.
	'fullscreen'         => true,
	'template_saving'    => true,
	'history'            => true,
);
```

You'll have some work to do besides that, though, like setting `editor_integration => false` (I won't even try to explain what's this all about, in short -- TinyMCE magic).

Good luck.

**Comment by dmbostan** [comment]
Nice! Looks promising! Thank you.

**Comment by dmbostan** [comment]
One more thing: how to correctly display the output of builder?

**Comment by andreiglingeanu** [comment]
The idea is simple - you should translate resulting JSON into the rendered shortcodes - and do this reliably.

That's how this is done by default in Page Builder: https://github.com/ThemeFuse/Unyson-PageBuilder-Extension/blob/master/class-fw-extension-page-builder.php#L310

Notice that you don't have any Post idea in Theme Settings, the post there is used just as a data storage.

**Comment by dmbostan** [comment]
Done. Thanks!
```
function show_pb_footer() {
	$builder_data = fw_get_db_settings_option('pboption');
	$option_type = fw()->backend->option_type('page-builder');
return str_replace('\\', '\\\\', // WordPress "fixes" the slashes
	$option_type->json_to_shortcodes( $builder_data['json'] )
);
}

echo do_shortcode(show_pb_footer());
```
