### ISSUE TITLE
Get array of post types that use page builder

### ISSUE THREAD

**Issue by dmbostan** [ThemeFuse/Unyson-PageBuilder-Extension#75]
Hi! 

I try to use `fw_get_db_ext_settings_option('page-builder', 'post_types');` in functions.php, but it gives that the function is undefined.

How can we solve this ?

**Comment by andreiglingeanu** [comment]
You should really wait for unyson to be fully initialized before using any of its functionality by hooking into the [`fw_init`](https://github.com/ThemeFuse/Unyson/blob/v2.6.8/framework/bootstrap.php#L111) action, like that:

```php

add_action('fw_init', 'my_hook');

function my_hook() {
  // use unyson functions
}

```


<hr>

_PRO TIP_: You can bootstrap unyson manually by calling `_action_init_framework()` manually, which will try to bootstrap the framework a bit _earlier_. Note that this feature is not supported officially and may be changed over time - you're on your own if you try to do such a scary thing and I'm pretty sure you'll never need it anyway.

**Comment by dmbostan** [comment]
Nice! Thanks.
