### ISSUE TITLE
Get all page builder data from a certain page?

### ISSUE THREAD

**Issue by dmbostan** [ThemeFuse/Unyson-PageBuilder-Extension#76]
Noob question, however can't find relevant info:

How to get the entire page builder array from a certain page? Not an option, but the entire thing.

Thank you in advance.

**Comment by dmbostan** [comment]
fw_print(get_post_meta( get_the_ID(), 'fw:opt:ext:pb:page-builder:json' ), true);

**Comment by moldcraft** [comment]
```php
fw_get_db_post_option(get_the_ID(), 'page-builder/json');
```
