### ISSUE TITLE
Custom backend option needed

### ISSUE THREAD

**Issue by dmbostan** [ThemeFuse/Unyson-PageBuilder-Extension#77]
Hi!

How can I add a custom option like this:
```
array(
    'type'  => 'text',
    'value' => 'default value',
    'attr'  => array( 'class' => 'custom-class', 'data-foo' => 'bar' ),
    'label' => __('Label', '{domain}'),
    'desc'  => __('Description', '{domain}'),
    'help'  => __('Help tip', '{domain}'),
    'blablabla' => true // or false
)
```
**'blablabla' => true // or false** is very much needed.

**Comment by andreiglingeanu** [comment]
What would you want to achieve with that?

**Comment by dmbostan** [comment]
@andreiglingeanu I think you are right. I had an idea about CSS delivery improvement, but you just gave me another idea. Thanks!

**Comment by dmbostan** [comment]
@andreiglingeanu is there a way to add the `blablabla` mentioned above for each built-in options? I just need a way to overwrite the current built-in options. I might not need to create new ones.

**Comment by dmbostan** [comment]
Got it on my own. Closing the issue.

**Comment by GheorgheP** [comment]
No, all options are controlled by options type itself, except for standard `type`, `desc`, `label`, `help`.

**Comment by dmbostan** [comment]
Thanks!
