### ISSUE TITLE
Hook into `_theme_filter_prevent_autop` to add content 

### ISSUE THREAD

**Issue by MikeiLL** [ThemeFuse/Unyson-PageBuilder-Extension#78]
I'm using the [fullpage.js](http://www.alvarotrigo.com/fullPage/) plugin which require's it's `sections` to be direct descendants of the wrapper. If I want to be able to add a default footer _within_ the `pagebuilder` `div`  by default, is there a filter which will make `_theme_filter_prevent_autop` accessible?

Or to add a default page builder template within the theme?

**Comment by moldcraft** [comment]
Have you tried via your own filter which will be executed before page-builder's filter?

```php
add_filter( 'the_content', '_filter_theme_change_pb_content', 1 );
function _filter_theme_change_pb_content($content) {
    if (
        function_exists('fw_ext_page_builder_is_builder_post')
        &&
        fw_ext_page_builder_is_builder_post()
    ) {
        $content .= '<div>Your Footer</div>';
    }

    return $content;
}
```

**Comment by MikeiLL** [comment]
Perfect, man. Thank you!
