### ISSUE TITLE
Button customization

### ISSUE THREAD

**Issue by Ranieripanc** [ThemeFuse/Unyson-PageBuilder-Extension#79]
Hi all,

I'd just want to customize the "Button" element in Unyson (content element) to build a standard menu in a purchased theme. I've tried to understand how to get there but didn't find any css or styling option for this.
Any help would be greatly appreciated.
Thanks
Ranieri

![image](https://cloud.githubusercontent.com/assets/24810632/21523089/319f6dd8-cd0b-11e6-8344-2cc1694dbf3d.png)

**Comment by moldcraft** [comment]
Hello,

Every shortcode has options, view and assets (also dynamic css). More info in [the docs](http://manual.unyson.io/en/latest/extension/shortcodes/index.html#content)

**Comment by Ranieripanc** [comment]
Yes, I've found that, thank you.
I'm not a programmer but I believe I can work this out.
The only thing I miss is how to attribute more styles to different buttons, i.e. I need at least 4 different button styles. Can you point this out?
Thanks 👍

**Comment by moldcraft** [comment]
Sorry, I don't think as a non programmer you will be able to deal with this framework. You will need to combine many options arrays and write some php code that will generate the dynamic css.

**Comment by Ranieripanc** [comment]
Yes I understand and agree but I want to try at least, since I have to deliver the next week a site prototype. Do you know of any examples of this kind, if any?

**Comment by moldcraft** [comment]
I don't have any good copy/paste examples.

Default button options have something similar [1](https://github.com/ThemeFuse/Unyson-Shortcodes-Extension/blob/b6674bee2131c29a614068765f96b69aa249651a/shortcodes/button/options.php#L31-L42) > [2](https://github.com/ThemeFuse/Unyson-Shortcodes-Extension/blob/b6674bee2131c29a614068765f96b69aa249651a/shortcodes/button/views/view.php#L2)

**Comment by Ranieripanc** [comment]
Thanks!
