### ISSUE TITLE
Cannot remove temporary directory

### ISSUE THREAD

**Issue by kimannou** [ThemeFuse/Unyson-PageBuilder-Extension#80]
hi guys,
first let me thank you for this greate masterpeice.
But in my hosting server, i wanted to install the page builder extension after installing the unyson plugin, but i get this mesage : 
`Cannot remove temporary directory: wp-content/plugins/unyson/tmp`
So i couldn't do anything and nothing is installed.
How could i surpass that problem ? 
thank you in advance

**Comment by moldcraft** [comment]
Hello,
Can you send me your admin and ftp credentials to `moldcraft[at]email.com`?

**Comment by GheorgheP** [comment]
I think we can close this issue due to inactivity.
