### ISSUE TITLE
Page Builder Extension Download Problem

### ISSUE THREAD

**Issue by onioid** [ThemeFuse/Unyson-PageBuilder-Extension#82]
Hi,
Thanks for the plugin. 
I would like to use it, but get this message when selecting the download button in Wordpress under 'Available Extensions':

Failed to access Github repository "ThemeFuse/Unyson-Shortcodes-Extension" releases. (Response code: 403)

I have the same problem with Breadcrumbs.
I downloaded the extension from here (Github) to my computer, but how/where do I upload/install it to Wordpress? I tried to upload it as a plugin to no avail, and got this:

Unpacking the package…
Installing the plugin…
The package could not be installed. No valid plugins were found.
Plugin install failed.
Return to Plugin Installer

Maybe ftp? But unsure to where.

Thanks in advance and best with the project!

**Comment by GheorgheP** [comment]
The Page Builder extension you need to add in `wp-content/plugins/unyson/framework/extensions/shortcodes/extensions`.

Do not forget to rename the extensions folder to `page-builder`

**Comment by zannaSenior** [comment]
Hi,
it looks a great plugin, but I can't install the page builder extension. I purchased Grand theme by Energetic Themes (wich includes Unyson). Developing a websites on wamp local server (windows 10), when I press the download button for Page builder extension I get the following error:
"Cannot move "C:/wamp/www/sinter/wp-content/plugins/unyson/tmp/Unyson-PageBuilder-Extension-1.6.13/includes" to "C:/wamp/www/sinter/wp-content/plugins/unyson/framework/extensions/shortcodes/extensions/page-builder/includes".
Users have complete control of the www folder (and subfolders).

Thanks in advance.

**Comment by premalk** [comment]
Hi. I have solved this problem just now. First of all you can deactivate your all plugins and then install the page builder extension again. I hope it will work.
I solved this problem by this technique after 4 hours. 


Thank you
