### ISSUE TITLE
missing fields in my page editor

### ISSUE THREAD

**Issue by galia1902** [ThemeFuse/Unyson-PageBuilder-Extension#86]
![screen shot 2017-04-25 at 5 04 35 pm](https://cloud.githubusercontent.com/assets/28009698/25390050/105296c8-29db-11e7-9f0a-11047faf5707.png)

I'm missing the "custom class" and "custom id" in another domain I've uploaded Unyson to. what can be done to make them appear?

**Comment by GheorgheP** [comment]
The **Custom Class** and **custom Id** options are added by the theme author in the **Section** shortcode options. Please contact the theme author and review why the options do not appear.
