### ISSUE TITLE
Problem with offline activation

### ISSUE THREAD

**Issue by mvpenzin** [ThemeFuse/Unyson-PageBuilder-Extension#88]
Hi!

I have an offline server for development.
Unyson framework was easily installed offline.
But something went wrong with the Page Builder extension.

I download and placed it on the path \wp-content\plugins\unyson\framework\extensions\
Next to the Page Builder appeared button "Activate".
After press this button WP writes: "Cannot activate the Builder extension because it is not installed. Install"
If I press "Install" then WP trying to connect with github: "Failed to access Github repository "ThemeFuse/Unyson-Builder-Extension" releases. (cURL error 28: Connection timed out after 5000 milliseconds)"

How can I activate Page Builder offline?
After press this button WP sad me: "Cannot activate the Builder extension because it is not installed. Install"
If I press "Install" then WP trying to connect with github: "Failed to access Github repository "ThemeFuse/Unyson-Builder-Extension" releases. (cURL error 28: Connection timed out after 5000 milliseconds)"

How can I activate Page Builder offline?

**Comment by GheorgheP** [comment]
You need to install all required extensions manually in this case, because the Page Builder Extensions requires the [Builder](https://github.com/ThemeFuse/Unyson-PageBuilder-Extension) extension to be installed and Unyson wants to download it from repository but cannot due to internet connection limitation.

**Comment by mvpenzin** [comment]
Exactly!
Page Builder and Builder are different extensions!
THNX!

But.. Something went wrong again..
Fatal error: Call to a member function load_shortcodes() on null in \wp-content\plugins\unyson\framework\extensions\page-builder\class-fw-extension-page-builder.php on line 111

**Comment by GheorgheP** [comment]
The `Page Builder` extensions is a sub-extension of the [Shortcodes](github.com/ThemeFuse/Unyson-Shortcodes-Extension/) extension. It is installed in the **Shortcodes** extension dir:

```
/wp-content/plugins/unyson/framework/extensions/shortcodes/extensions/page-builder
```
