### ISSUE TITLE
Unyson elements gives error to elements when editing page with page builder HEAD IS EXPLODING

### ISSUE THREAD

**Issue by banglacow** [ThemeFuse/Unyson-PageBuilder-Extension#89]
I am using themeforest themefuse planup event theme for wordpress

The following pictures describe the immense mental torture
I've had for the past 48hours

Unyson shows me error when I drag the elements to the page. Clicking on it show "error not found"

I tried everything.
1.reinstalling wordpress
2.reinstalling plugins
3.reinstalling themes

![manage themes runpilgrim wordpress](https://cloud.githubusercontent.com/assets/28556289/25839202/47bac1dc-34c9-11e7-9396-1c79be75a32e.png)
![manage themes runpilgrim wordpress1](https://cloud.githubusercontent.com/assets/28556289/25839199/47acd46e-34c9-11e7-9ae9-39e3e07168cd.png)
![manage themes runpilgrim wordpress2](https://cloud.githubusercontent.com/assets/28556289/25839200/47ae4218-34c9-11e7-8027-bab3203805ac.png)
![manage themes runpilgrim wordpress3](https://cloud.githubusercontent.com/assets/28556289/25839201/47b34ab0-34c9-11e7-9cbf-02a9b0341c26.png)

**RESPECT**
I now have immense respect for what you guys do. Thank you do very much.
Scrolled through the issues but didn't find any solution.

Eternally grateful to anyone who can help

**Comment by GheorgheP** [comment]
Hi,

First of all thank you for appreciation.

In case you are about this theme [Plan Up](https://themeforest.net/item/planup-event-booking-wordpress-theme/14049587), then you have to know that it is not developed by ThemeFuse. It is developed by another author, but it is using the Unyson framework developed by ThemeFuse.

Does the error appear only on specific shortcodes or on all of them?
You need to contact the theme author and ask for assistance and from what I see the shortcodes are developed/edited by theme author.

In main time can make some debugging tests to find out from where the error may come.

 - Activate the `WP_DEBUG` by setting the `define( 'WP_DEBUG', false );` to `define( 'WP_DEBUG', true );` in `wp-config.php`. 
 - Open browser **Developer Tools** (by hitting F12)
 - In **Network** section check the **XHR** filter
 - Then try to open the problematic shortcode
 - In **Network** section will notice that there was made an request. Look in that request details and provide that information to your theme developer so he could provide you a solution.

![](https://static.md/42bfa0f8c4f93dbb0a0046bcc0b6dcff.png)

**Comment by banglacow** [comment]
[https://github.com/ThemeFuse/Unyson/issues/2578#issuecomment-300392413](https://github.com/ThemeFuse/Unyson/issues/2578#issuecomment-300392413)

thank you.... they were talking about it being a server config issue

i am head over tails over these ... what should I do?

Closing this

u are a angel

thank you
