### ISSUE TITLE
elements are saved with absolute paths making domain changes impossible 

### ISSUE THREAD

**Issue by alexitmp** [ThemeFuse/Unyson-PageBuilder-Extension#90]
I have created a wordpress site on my pc before moving it to the server. The localhost is way faster then the server. 
But when I tried to move the data to the server according to wordpress' tutorial I found that the images and some other elements didn't work. In the source code I found that the SRC-paths had "localhost" in them  which required me to edit the whole site again after moving it to the production server. These absolute paths to images etc. are not required and do not go according the Wordpress guidelines. 
I suggest relative paths for local files and absolute paths only for remote files.

**Comment by GheorgheP** [comment]
There are saved the URls, not paths. But I would recommend to use the Backup extension in order to migrate your site.

**Comment by JeSuis** [comment]
Its horrible you have to manually go into the db and update things, the backup extension also overwrote the db info in wp-config
