### ISSUE TITLE
Column popup size

### ISSUE THREAD

**Issue by dmbostan** [ThemeFuse/Unyson-PageBuilder-Extension#91]
Hi, guys!

Is there a way to change the popup size of columns in builder? I am using multiple tabs, and they look very bad inside.

Thank you in advance.

**Comment by ecksite** [comment]
You can override the column shortcode configuration which is used by the page builder. See the [documentation](http://manual.unyson.io/en/latest/extension/shortcodes/index.html#config-file)

by doing that, you can change the column's popup size by adding 
```php
popup_size'  => 'large', 
```

to the 'page_builder' array. 

for example: in your custom config.php:
```php
$cfg = array(
    'page_builder' => array(
        'popup_size'  => 'large',
    )
);
```
