### ISSUE TITLE
Hardcodes `http` even though wordpress uses `https`

### ISSUE THREAD

**Issue by JeSuis** [ThemeFuse/Unyson-PageBuilder-Extension#92]
Page builder hardcodes the full url for the asset using `http` even though the site uses `https`
This leads to content security issues and doesn't let the assets load.
If you switch to the default editor and insert an image it inserts it as `https` as it should, this seems to be an issue with the plugin.

**Comment by ViorelEremia** [comment]
What scripts I checked and there are no scripts loaded without protocol
