### ISSUE TITLE
Publish/Update Button Missing after activating Unyson-PageBuilder Extension

### ISSUE THREAD

**Issue by solamichealolawale** [ThemeFuse/Unyson-PageBuilder-Extension#93]
Hi, your plugin is great, just that today as i login to my admin dashboard, i updated the unyson plugin and when i try to create new post/event/page, the publish button is missing, while troubleshooting (deactivativing and reactivating plugins) I discovered that when i deactivate the PageBuilder  extension in Unyson, the publish button will dissapear and the "add new page" takes forever to load.

Please help as it is urgent and important; Thanks in advance

**Comment by ViorelEremia** [comment]
Hi, 
Please provide some details such as:
1. What theme do you use?
2. Your server configuration
3. Try and disable all plugins
4. Try to activate debug(recommended) or install a plugin such as debug bar

**Comment by solamichealolawale** [comment]
1. Woffice Intranet/Extanet Theme

2. cPanel Version | 60.0 (build 46)
   Apache Version | 2.2.31
   PHP Version | 5.4.45
   MySQL Version | 5.5.51-38.2
   Architecture | x86_64
   Operating System | linux

3. I have disabled all plugins, until i get to know that unyson page builder is the cause and cant deactivate the plugin, for my site is dependent  on it

4. Ive tried it, but its still the same

**Comment by ViorelEremia** [comment]
Sorry for long delay, you found the problem? I think is caused by a javasscript error or footer admin is not rendered stopped by an fatal error php, in short drop me your credentials from dashboard here : viorel[ a ] themefuse [[ dot ]] com
