### ISSUE TITLE
"Shortcodes" extension github repository "ThemeFuse/Unyson-Shortcodes-Extension" has no releases.

### ISSUE THREAD

**Issue by EasyMarketingSolutions** [ThemeFuse/Unyson-PageBuilder-Extension#96]
Hello, I installed a theme on wordpress. Finish installation i had this error when I want to install the page builder.

"Shortcodes" extension github repository "ThemeFuse/Unyson-Shortcodes-Extension" has no releases.

I don't know how it is solved. I hope you can help me.

**Comment by ViorelEremia** [comment]
https://github.com/ThemeFuse/Unyson/issues/2790
