### ISSUE TITLE
New CSS is setting all images height to auto and breaks a lot of things

### ISSUE THREAD

**Issue by dominicht** [ThemeFuse/Unyson-PageBuilder-Extension#97]
In frontend-grid.css, there is a new css rule:
`img {
    height: auto;
}`

I noticed that a lot of websites using Unyson now have disproportionate images. For example, if an image height was set directly on the <img> tag using the "height" attribute, it is now overriden with that new css rule for all images. There is also no way to revert this with CSS (display the image using the "height" attribute on the img instead of the CSS).

I don't think it is the best idea to apply a CSS attribute like this to ALL images. Is there a possible fix

**Comment by ViorelEremia** [comment]
https://github.com/ThemeFuse/Unyson/issues/2495
you can rewrite it, create in theme or child theme: framework-customizations/extensions/builder/static.php : 
`<?php defined( 'FW' ) or die();

if ( ! is_admin() ) {
	wp_register_style(
		'fw-ext-builder-frontend-grid',
		fw_get_template_customizations_directory_uri( '/extensions/builder/static/css/frontend-grid.css' ),
		array(),
		fw_ext('builder')->manifest->get_version()
	);
}`
Copy file from Unyson\framework\extensions\builder\static\css\frontend-grid.css to  framework-customizations/extensions/builder/static/css/frontend-grid.css and delete this line of code with img height.

**Comment by dominicht** [comment]
Thanks for the reply. Hovewer, overriding the whole CSS file isn't really a sustainable solution since this issue will most likely happen on any theme using the Unyson page builder.

The main issue is that `img { height: auto; }` is not overridable with CSS (you can set a different height, but you can't reset this rule). This rule in the CSS file overrides the "height" attribute of the tag, unlike the "style" attribute for example that would override the CSS.

This basically means that because of this rule, the "height" attribute of ALL images is useless!

In my opinion, this is still an issue.

**Comment by dominicht** [comment]
You can see this as a reference: https://stackoverflow.com/questions/44010645/remove-height-auto-using-css

**Comment by dominicht** [comment]
@ViorelEremia What do you think?
