### ISSUE TITLE
Is there is a way to export the json code saved by the builder into shortcodes in default wordpress editor?

### ISSUE THREAD

**Issue by alhoseany** [ThemeFuse/Unyson-PageBuilder-Extension#98]
Hi,
My client want to remove the builder and use the default wordpress editor instead with the shortcodes of the builder. we have more than 150 pages creating by the builder. is there is anyway to automate the process of getting the json code of the builder, convert to normal text with shortcodes and then save it in the default post content?

**Comment by ViorelEremia** [comment]
The key that contains json of shortocodes is fw:opt:ext:pb:page-builder:json you can extract and manipulate it as you like, test this code:
`wp_update_post(
	array(
		'ID'           => $post_id,
		'post_content' => function_what_parse_json( get_post_meta( $post_id, 'fw:opt:ext:pb:page-builder:json', true ) ),
	)
);`
