### ISSUE TITLE
Carousel module's "Add new item" button is hidden

### ISSUE THREAD

**Issue by nydame** [ThemeFuse/Unyson-PageBuilder-Extension#99]
At some point after initially adding images to a carousel, it becomes impossible to edit because the "Add new item" button is hidden. After removing that class name, the new item form appears, but when it is "saved", nothing actually happens.

**Comment by ViorelEremia** [comment]
Unyson by default don't have shortcode carousel, what is carousel shortcode or custom post type, provide more details how you added it, where, what class, maybe you mean slider type???

**Comment by nydame** [comment]
Ah,  my mistake; I will talk to theme developers. Sorry!
